# Rustfmt configuration for VEM project
# Follows C(K&R) style conventions with vertical import formatting
# Note: Some features require nightly toolchain (cargo +nightly fmt)

edition = "2024"

# Import formatting - skip formatting imports to preserve manual style
skip_children = true
imports_granularity = "Preserve"    # Preserve existing import structure
group_imports = "Preserve"          # Preserve existing grouping

# Use trailing commas for multi-line items
trailing_comma = "Vertical"

# Indentation
tab_spaces = 4
indent_style = "Block"
hard_tabs = false

# Line length
max_width = 120
use_small_heuristics = "Default"

# Import and use statement layout - disable reordering
reorder_imports = false
reorder_modules = false

# Newlines and spacing
newline_style = "Unix"
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0

# Miscellaneous formatting - disable aggressive reformatting
merge_derives = false
use_field_init_shorthand = false
use_try_shorthand = false
remove_nested_parens = false
normalize_comments = false
wrap_comments = false

# Control flow and match
match_block_trailing_comma = true
overflow_delimited_expr = false

# Space handling
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"

# Formatting style
format_code_in_doc_comments = false
format_macro_matchers = false
format_macro_bodies = true
format_strings = false

# Chain formatting - keep existing style
chain_width = 120
single_line_if_else_max_width = 100
fn_call_width = 120
struct_lit_width = 120
struct_variant_width = 120
array_width = 120
attr_fn_like_width = 120

# Struct and enum formatting
struct_lit_single_line = false
enum_discrim_align_threshold = 0