[book]
authors = ["ryo-arima"]
language = "en"
multilingual = false
src = "src"
title = "VEM Documentation"
description = "Documentation for VEM (Vim Environment Manager)"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
additional-css = []
additional-js = []
no-section-label = false
git-repository-url = "https://github.com/ryo-arima/vem"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/ryo-arima/vem/edit/main/docs/{path}"
site-url = "https://ryo-arima.github.io/vem/"
root-url = "https://ryo-arima.github.io/vem/"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true

[preprocessor.links]
# Convert README and other files to proper links

[output.html.fold]
enable = false
level = 0
