name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  approve:
    if: github.event.pull_request.user.login == 'ryo-arima'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Auto-approve PR
        env:
          # Note: GITHUB_TOKEN may not be able to approve PRs from the same user
          # due to GitHub security restrictions. If approval fails, consider using
          # a Personal Access Token from a bot account in AUTO_APPROVE_TOKEN secret.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve --repo ${{ github.repository }}