name: Auto Approve
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  approve:
    if: |
      github.event.pull_request.user.login == 'ryo-arima'
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v3
        with:
          # Use a dedicated PAT stored in repository secrets so the approval
          # is performed by a bot account (not github-actions[bot] / the PR author).
          github-token: ${{ secrets.AUTO_APPROVE_TOKEN }}