name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  build-and-upload:
    name: Build and Upload
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: vem-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: vem-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: vem-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: vem-macos-aarch64

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Prepare asset (Unix)
      if: runner.os != 'Windows'
      run: |
        cp target/${{ matrix.target }}/release/vem ${{ matrix.asset_name }}
        chmod +x ${{ matrix.asset_name }}
    
    - name: Prepare asset (Windows)
      if: runner.os == 'Windows'
      run: |
        cp target/${{ matrix.target }}/release/vem.exe ${{ matrix.asset_name }}
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: ./${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream